config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  root 'static_pages#home'

  get 'about'   => 'static_pages#about'
  get 'signup'  => 'users#new'
  get 'game'  => 'users#game'
  get 'levels' => 'static_pages#levels'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  match  '/users/add' => 'users#add', via: [:post, :get]
  
  resources :users
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save {self.name = name.downcase}
  validates :name, presence: true, length: { maximum: 50 },uniqueness: { case_sensitive: false }
  validates :age, presence: true, allow_nil: true
  validates :gender, presence: true, length: { maximum: 1 }, allow_nil: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  after_initialize :init
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
   def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
   # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
  	return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  def init
    self.levelNum ||= 1
    self.speedup ||=1
    self.corrRow ||=0
    self.gridSize ||= 3
    self.levelType ||= 0
    self.color ||= "blue"
    self.group ||= 0+rand(1);
    self.attempts ||=0
    self.totalCorrect ||=0
  end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
    def create
    user = User.find_by(name: params[:session][:name].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      remember user
      redirect_to user
      # Log the user in and redirect to the user's show page.
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid username/password combination'
      render 'new'
    end
  end

  def destroy
  	log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
  def game

  end
  def levels
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :js, :json

  def show
    @user = User.find(session[:user_id])
  end
  def index
  end
   def game 
    @user = User.find(session[:user_id])

  end
  def new
    @user = User.new
  end
    def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Gridworkz!"
      redirect_to @user# Handle a successful save.
    else
      render 'new'
    end
end
def add
   user = User.find(params[:id])
   user.speedup = params[:speedup]
   user.corrRow = params[:correctRow]
   user.gridSize = params[:gridSize]
   user.levelNum = params[:levelNum]
   user.levelType = params[:levelType]
   user.attempts = params[:attempts]
   user.levelData = params[:levelInfo]
   user.totalCorrect = params[:totalCorr]
   user.save
   render :nothing => true
   head :ok
       
  end
  private

    def user_params
      params.require(:user).permit(:name, :age, :gender, :password,
                                   :password_confirmation)
    end
    def add_info_with_para p = {}
      @user = User.find(session[:user_id])
      @user.corrRow = params[:correctRow]
      @user.gridSize = params[:gridSize]
      @user.levelNum = params[:levelNum]
      @user.levelType = params[:levelType]
      @user.attempts = params[:attempts]
      @user.levelData = params[:levelInfo]
      @user.totalCorrect = params[:totalCorr]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
def log_in(user)
    session[:user_id] = user.id
  end
   # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
   def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  def logged_in?
    !current_user.nil?
  end
   # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  def log_out
   	forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.name.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
     
      <div class="container">
         <% if logged_in? %>
       	    <%= link_to "Gridworkz", game_path,  id: "logo" %>
          <% else %>
            <%= link_to "Gridworkz", "/", id: "logo" %>
          <% end %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            
            <% if !logged_in? %>
              <li><%= link_to "Home",   '/' %></li>
              <li><%= link_to "About", about_path%></li> 
              <li><%= link_to "Log in", login_path %></li>
              <li><%= link_to "Sign up", signup_path %></li>
              
            </li>
          <% else %>
              <li><%= link_to "Game",   game_path%></li>
              <li><%= link_to "About", about_path%></li> 
              <li><%= link_to "Levels", levels_path %></li>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= button_to "Logout", logout_path, :method => :delete %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= Gon::Base.render_data({}) %>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
    
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Home | Gridworkz</title>
  </head>
  <body>
    <h1> <%= image_tag("Logo.png", alt: "Rails logo") %>
    </h1>
    <h2>
      A game to test your spacial relations skills. 
    </h2>
    <h3>
    	Below is a sample of a level with a 5x5 grid size. On the left will be a given grid, in the middle instructions for rotating and on the right is the correctly rotated reproduced grid.</h3>
    <p>
    	<%= image_tag("instructionPic1.png",alt:"instructionPic") %>
    	<%= image_tag("instructionPic2.png",alt:"instructionPic") %>
    	<%= image_tag("instructionPic3.png",alt:"instructionPic") %>

    	</p>
  </body>
</html>

app/views/static_pages/game.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel='stylesheet' type='text/css' href='custom.css.scss'/>
</head>
  <h1>
<script>
  var instructions = ["Clockwise 90", "Counter-Clockwise 90", "Clockwise 180", "Counter-Clockwise 180", "Clockwise 270", "Counter-Clockwise 270"];
  document.write(instructions[0].bold());
  var test = <%= @userlist.to_json %>;
  //JSON.stringify(test);
  document.write(gon.test);
  
</script>
  <IMG STYLE="position:absolute; TOP:520px; LEFT:350px; WIDTH:775px; HEIGHT:130px" SRC="assets/clockwise90.png">
  <!--<%=image_tag("clockwise90.png", class: "smiley", alt:"smiley") %> -->
</h1>
  <body> 
    <input type="button" name="button1" value="Done" style="position: absolute; left: 650px; top: 300px; width: 200px; " onclick="done()" />
    <script type="text/javascript">
    
    //var initialTime=getTime();
    
      var player = initialize(3);
      /* function to make the clickable grid and to determine what happens when the block is clicked */
      var grid = clickableGrid(3,3,function(el,row,col,i){
      if(el.className == '' || el.className == 'unclicked'){
       el.className='clicked';
       player[row][col] = 1; 
        }
      else{
        el.className ='unclicked';
        player[row][col] = 0;
      }
      });
      /*mkaes the given grid*/
      var grid1 = staticGrid(3,3,function(el,row,col,i){

      });


      /*adds the grids to the page*/
      document.body.appendChild(grid);
      document.body.appendChild(grid1);

      var da = block(4);
      /*call to convert double array to single array*/
      var newar = convert(da);
      /*fills squares based on grid generated into an array*/
      var filled = fill(newar);
      var inst = ["Clockwise", "90"];
      var solved = solver(3, inst, da);
      
    
    function done(){//TODO: write empty grid function
      var temp = arraysIdentical(3,solved,player);
      if(temp){
      var emp = empty(18);
      player = initialize(3);
      document.body.removeChild(grid);
      document.body.removeChild(grid1);
      grid = clickableGrid(3,3,function(el,row,col,i){
      if(el.className == '' || el.className == 'unclicked'){
       el.className='clicked';
        player[row][col] = 1; 
        }
      else{
        el.className ='unclicked';
        player[row][col] = 0; 
      }
      });
      document.body.appendChild(grid);
      document.body.appendChild(grid1);
      da = block(3);
      /*call to convert double array to single array*/
      newar = convert(da);
      /*fills squares based on grid generated into an array*/
      filled = fill(newar);
      solved = solver(3, inst, da);
    }
    else{
        alert("Not quite. Try again!");
    }
  
  
}

  function arraysIdentical(size, a, b) {
    var i = 0;
    var j = 0;
    for(i; i<size; i++){
      for(j; j<size; j++){
        if(a[i][j]!=b[i][j]){
          return false;
        }
      }
    }
    return true;
    }

  /*function that getsNewTime */
  function getInterval(oldtime)
  {

    var time=getTime();
    return time-oldtime;

  }

     /* function that builds the clickable grid*/
      function clickableGrid( rows, cols, callback ){
        var i=0;
        var grid = document.createElement('table');
        grid.className = 'grid';
        for (var r=0;r<rows;++r){
          var tr = grid.appendChild(document.createElement('tr'));
          for (var c=0;c<cols;++c){
            var cell = tr.appendChild(document.createElement('td'));
            cell.addEventListener('click',(function(el,r,c,i){
              return function(){
                callback(el,r,c,i);
                }
            })(cell,r,c,i),false);
          }
        }
        return grid;
      }



      /*fucntion that builds given grid*/
     function staticGrid( rows, cols, callback ){
        var i=0;
        var grid = document.createElement('table');
        grid.className = 'grid1';
        for (var r=0;r<rows;++r){
          var tr = grid.appendChild(document.createElement('tr'));
          for (var c=0;c<cols;++c){
              var cell = tr.appendChild(document.createElement('td'));            
            cell.addEventListener('click',(function(el,r,c,i){
              return function(){
                callback(el,r,c,i);
                }
            })(cell,r,c,i),false);
          }
        }
        return grid;
      }

      /*fucntion that fills in the squares of the given grid*/
      function fill(fill){
        var td = document.getElementsByTagName("td");
        var size = fill.length;
        var i = 0, tds = td.length;
        for(i; i<size; i++){
          if(fill[i] == 1){
            td[tds-size+i].setAttribute("style","background:green;");
        }
      }
    }
      /*function that clears grids*/
      function empty(size){
        var td = document.getElementsByTagName("td");
        var i = 0, tds = td.length;
        for(i; i<tds; i++){
            td[i].setAttribute("style","background:white;");

          
        }
      }


      /*function that converts a 2-d array to a single array*/
      function convert(doubleArray){
    return doubleArray.join().split(",");
      }

 

      
    
       /*function that solves the level*/
      function solver(rows, instruction, givenSquare){
        var solvedSquare = initialize(rows);
        if((instruction[0]== "Clockwise" && instruction[1] == "90")||(instruction[0]== "Counter-Clockwise"&& instruction[1] == "270")){
       for(var i = 0; i<rows; i++){
        for(var j = 0; j<rows; j++){
            
          solvedSquare[j][rows-1-i] = givenSquare[i][j];
        }}}
      else if((instruction[0]== "Clockwise"&& instruction[1] == 180)||(instruction[0]== "Counter-Clockwise"&& instruction[1] == "180")){
      for(var i = 0; i<rows; i++){
        for(var j = 0; j<rows; j++){
          solvedSquare[rows-1-i][rows-1-j] = givenSquare[i][j];
          
        }}}
      else if((instruction[0]== "Clockwise"&& instruction[1] == "270")||(instruction[0]== "Counter-Clockwise"&& instruction[1] == "90")){
      for(var i = 0; i<rows; i++){
        for(var j = 0; j<rows; j++){
          solvedSquare[rows-1-j][i] = givenSquare[i][j];
        }}}
      return solvedSquare;
    }

    //returns an array of instruction 
    
      function instructions(){
    var rotation = ["Clockwise", "Counter-Clockwise"];
    var degree = ["90","180","270"];
    var randomRotation=Math.floor(Math.random()*2);//0-1
    var randomDegree = Math.floor(Math.random()*3);//0-2
    var instruction = new array;
    instruction[0] = rotation[randomRotation];
    instruction[1] = degree[randomDegree];
    return instruction;
   }
   function initialize(gridsize)
{ 
  //alert("In initialize");
  var result = new Array();
  for (var i = 0; i <gridsize; i++) 
  {
    result[i]=new Array();
    for (var j = 0; j <gridsize; j++) 
    {     
      result[i][j]=0; 
    }//end inner for loop
  }//end outer for loop
  //alert("done initialising");
  //alert(result);
  return result;
}

   function corners(gridsize)
{
  var result = initialize(gridsize);
  var filledSquares=Math.floor(gridsize*gridsize/3)-1;//30% rounded down -first point
  var starti = Math.floor(Math.random()*gridsize);//0-(gridsize-1)
  var startj = Math.floor(Math.random()*gridsize);//0-(gridsize-1)
    result[starti][startj]=1;
  var tempi=starti;
  var tempj=startj; 
  while(filledSquares!==0)  //fill in squares
  {
    var direction=Math.floor(Math.random()*4);
    //0->i--, 1->i++, 2->j--, 3->j++; pick a random direction to go

    switch(direction)
    {
      case 0:
        tempi=starti-1; tempj=startj-1;
        break;
      case 1:
        tempi=starti+1; tempj=startj+1;
        break;
      case 2:
        tempj=startj-1; tempi=starti+1;
        break;
      case 3:
        tempj=startj+1; tempi=starti-1;
        break;
      default:
       // console.log('something went wrong');
        break;
    }//end switch case
   // console.log("printing i%i then j%i",tempi,tempj);
  
    if(tempi<gridsize && tempj<gridsize && tempi>=0 && tempj>=0)//not out of bounds && 
    {
     // console.log("not out of bounds");
      if(result[tempi][tempj]==0)//we arent refillling something filled
      {
       // console.log("we arent refillling anything");
          if(corneredCorners(tempi,tempj,gridsize,result)==1)
          {
            result[tempi][tempj]=1;
            filledSquares--;
            starti = tempi;
            startj = tempj;
           // console.log("decrementing in corners printing i%i and j%i",tempi,tempj);
          }
      }
    }
    //else
    //{
      //if(direction===0)
      //{filledSquares--;}
  //  }
  }//end loop
  console.log("exited while loop of corners, returning");
  console.log(result);
  return result;  
}
function corneredCorners(i,j,gridsize,grid)//TODO: finish this and corneredMix
//called: coneredCorners(tempi, tempj, gridsize, grid)
{
  var result;
  if(i==0 || j==0 || i==gridsize-1 ||j==gridsize-1)
  //are we in a literal corner of a grid only one place to go
  {
   // console.log("corner case");
    if(i==0 && j==0)//only increase
    {
      if(grid[i+1][j+1]==1)
        result = 1;
    }
    if (i==0 &&j==gridsize-1) 
    {
      if(grid[i+1][j-1]==1)
        result = 1;
    }
    if(i==gridsize-1 && j==0)
    {
      if(grid[i-1][j+1]==1)
        result = 1;
    }
    if(i==gridsize && j==gridsize)
    {
      if(grid[i-1][j-1]==1)
        result = 1;
    }
  }
  else
  {
    //console.log("normal case")
    if(grid[i+1][j+1]==1 || grid[i+1][j-1]==1 || grid[i-1][j+1]==1 || grid[i-1][j-1]==1)
      {result = 1;}
    else{
    result = 0;}
  }
  //console.log("result :",result);
  return result;
}

        function block(gridsize)
  {
    var result = new Array();
    var row=Math.floor(Math.random()*2);//0-1
    var rowNumber = Math.floor(Math.random()*gridsize);//0-(gridsize-1)
    for (var i = 0; i <gridsize; i++) 
    {
      result[i]=new Array();
      for (var j = 0; j <gridsize; j++) 
      {     
        if(row==1)//row not column
        {
          if(j==rowNumber)
            { result[i][j]=1; } 
          else
            { result[i][j]=0; }       
        }//end row
        else//column
        {
          if(i==rowNumber)
          { result[i][j]=1; }
          else
          { result[i][j]=0; }
        }//end column
      }//end inner for loop
    }//end outer for loop
    return result;
  }
     
    </script>
    
     </body>
     </html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Home | Gridworkz</title>
  </head>
  <body>
    <h1> <%= image_tag("Logo.png", alt: "Rails logo") %>
    </h1>
    <h2>
      Welcome to Gridworkz, the spacial relation game. 
    </h2>
    <h3>
    	Please <%= link_to "login", login_path %> or <%= link_to "sign up", signup_path %> to play!
    </h3>
  </body>
</html>

app/views/static_pages/levels.html.erb
<!DOCTYPE html>
<html>
	<head>
		<link rel='stylesheet' type='text/css' href='custom.css.scss'/>
	</head>
<body>
    <script type="text/javascript">
    </script>
<!--
    <%=image_tag("lockicon3.png", class: "lock", alt:"lock") %> 
    <%=image_tag("lockicon4.png", class: "lock4", alt:"lock") %>
    <%=image_tag("lockicon5.png", class: "lock5", alt:"lock") %>
    <%=image_tag("lockicon6.png", class: "lock6", alt:"lock") %>
    <%=image_tag("lockicon7.png", class: "lock7", alt:"lock") %>
    <%=image_tag("lockicon8.png", class: "lock8", alt:"lock") %>
    <%=image_tag("lockicon9.png", class: "lock9", alt:"lock") %>
    <%=image_tag("lockicon10.png", class: "lock10", alt:"lock") %>
//-->
  	<input type="button" name="button1" value="3 x 3" style="position: absolute; left: 75px; top: 300px; width: 100px;" onclick="window.location='game'" 
    />

    <IMG STYLE="position:absolute; TOP:330px; LEFT:110px; WIDTH:30px; HEIGHT:30px" SRC="assets/lockicon3.png">

  	<input type="button" name="button2" value="4 x 4" style="position: absolute; left: 225px; top: 300px; width: 100px;" onclick="window.location='game'" 
    />

    <IMG STYLE="position:absolute; TOP:330px; LEFT:260px; WIDTH:30px; HEIGHT:30px" SRC="assets/lockicon3.png">

  	<input type="button" name="button3" value="5 x 5" style="position: absolute; left: 375px; top: 300px; width: 100px;" onclick="window.location='game'" 
    />

    <IMG STYLE="position:absolute; TOP:330px; LEFT:410px; WIDTH:30px; HEIGHT:30px" SRC="assets/lockicon3.png">

  	<input type="button" name="button4" value="6 x 6" style="position: absolute; left: 525px; top: 300px; width: 100px;" onclick="window.location='game'" 
    />

    <IMG STYLE="position:absolute; TOP:330px; LEFT:560px; WIDTH:30px; HEIGHT:30px" SRC="assets/lockicon3.png">

  	<input type="button" name="button5" value="7 x 7" style="position: absolute; left: 675px; top: 300px; width: 100px;" onclick="window.location='game'" 
    />

    <IMG STYLE="position:absolute; TOP:330px; LEFT:710px; WIDTH:30px; HEIGHT:30px" SRC="assets/lockicon3.png">

  	<input type="button" name="button6" value="8 x 8" style="position: absolute; left: 825px; top: 300px; width: 100px;" onclick="window.location='game'" 
    />

    <IMG STYLE="position:absolute; TOP:330px; LEFT:860px; WIDTH:30px; HEIGHT:30px" SRC="assets/lockicon3.png">

  	<input type="button" name="button7" value="9 x 9" style="position: absolute; left: 975px; top: 300px; width: 100px;" onclick="window.location='game'" 
    />

    <IMG STYLE="position:absolute; TOP:330px; LEFT:1010px; WIDTH:30px; HEIGHT:30px" SRC="assets/lockicon3.png">

  	<input type="button" name="button8" value="10 x 10" style="position: absolute; left: 1125px; top: 300px; width: 100px;" onclick="window.location='game'" 
    />

    <IMG STYLE="position:absolute; TOP:330px; LEFT:1160px; WIDTH:30px; HEIGHT:30px" SRC="assets/lockicon3.png">

  </body>
 </html>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
     <%= render 'shared/error_messages' %>

      <%= f.label :username %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :age %>
      <%= f.text_field :age, class: 'form-control' %>

      <%= f.label :gender, "Gender (M/F)" %>
      <%= f.text_field :gender, class: 'form-control' %>

      <%= f.label :password, "Password(Minimum 6 characters) " %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name%>
        
      </h1>
    </section>
  </aside>
</div>

<form method="post">
        <fieldset>
                <legend>Block Color</legend>
                        <ul>
                            <label for="Red" class= "label-align">Red 
                              <input type="radio" name="color" id="Red" value="Red">
                            </label>
                            <label for="Orange" class= "label-align">Orange 
                              <input type="radio" name="color" id="Orange" value="Orange">
                            </label>
                            <label for="Yellow" class= "label-align">Yellow
                              <input type="radio" name="color" id="Yellow" value="Yellow">
                            </label> 
                            <label for="Green" class= "label-align">Green 
                              <input type="radio" name="color" id="Green" value="Green">
                            </label>
                            <label for="Blue" class= "label-align">Blue
                              <input type="radio" name="color" id="Blue" value="Blue">
                            </label>
                            <label for="Purple" class= "label-align">Purple
                              <input type="radio" name="color" id="Purple" value="Purple">
                            </label> 
                            <label for="Pink" class= "label-align">Pink 
                              <input type="radio" name="color" id="Pink" value="Pink">
                            </label>
                           
                        </ul>
                      
        </fieldset>
</form>